Parameters:
  apigatewayname:
    Type: String
    Default: flume
    Description: Provide API Gateway Name
  s3bucketname:
    Type: String
    Default: flume
    Description: Existing S3 Bucket Name
  verifytokenvalue:
    Type: String
    Default: <VERIFY>
    Description: Set Unique Verification Value
Resources:
  roleC7B7E775:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
  roleDefaultPolicy7C980EBA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: s3bucketname
                  - /*
        Version: "2012-10-17"
      PolicyName: roleDefaultPolicy7C980EBA
      Roles:
        - Ref: roleC7B7E775
  apirole85D7B7F5:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
  flume9B71057B:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ZipFile: |-
          import boto3
          import datetime
          import gzip
          import json
          import os
          import uuid

          def handler(event, context):

              print(event)

              try:

                  if event['queryStringParameters']['verify'] == os.environ['VERIFY']:

                      uniq = str(uuid.uuid4())

                      with gzip.open('/tmp/'+uniq+'.json.gz', 'wb') as g:
                          g.write((str(event)+str('\n')).encode())
                      g.close()

                      year = datetime.datetime.now().year
                      month = datetime.datetime.now().month
                      day = datetime.datetime.now().day
                      hour = datetime.datetime.now().hour

                      s3 = boto3.client('s3')

                      bucket = os.environ['BUCKET']
                      prefix = os.environ['PREFIX']
                      key = f'{prefix}/year={year}/month={month}/day={day}/hour={hour}/{uniq}.json.gz'

                      s3.upload_file('/tmp/'+uniq+'.json.gz', bucket, key)

                      code = 200
                      msg = 'Shipped: '+key

                  else:

                      code = 404
                      msg = 'Where the Internet Ends'

              except:
                  
                  code = 404
                  msg = 'Where the Internet Ends'

              return {
                  'statusCode': code,
                  'body': json.dumps(msg)
              }
      Environment:
        Variables:
          BUCKET:
            Ref: s3bucketname
          PREFIX: logs
          VERIFY:
            Ref: verifytokenvalue
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - roleC7B7E775
          - Arn
      Runtime: python3.13
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
      Timeout: 30
    DependsOn:
      - roleDefaultPolicy7C980EBA
      - roleC7B7E775
  logs0B6081B1:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - /aws/lambda/
            - Ref: flume9B71057B
      RetentionInDays: 14
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  apiC8550315:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description:
        Ref: apigatewayname
      Name:
        Ref: apigatewayname
      ProtocolType: HTTP
      Tags:
        GitHub: https://github.com/jblukach/flume
  apiDefaultStage04B80AC9:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: apiC8550315
      AutoDeploy: true
      StageName: $default
      Tags:
        GitHub: https://github.com/jblukach/flume
  apiPOSTlogsintegrationE991E333:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: apiC8550315
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::GetAtt:
          - flume9B71057B
          - Arn
      PayloadFormatVersion: "2.0"
  apiPOSTlogsintegrationPermission11549B75:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - flume9B71057B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /*/*/logs
  apiPOSTlogs82DE9661:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: apiC8550315
      AuthorizationType: NONE
      RouteKey: POST /logs
      Target:
        Fn::Join:
          - ""
          - - integrations/
            - Ref: apiPOSTlogsintegrationE991E333

