Parameters:
  apigatewayname:
    Type: String
    Default: flume
    Description: Provide API Gateway Name
Resources:
  secret4DA88516:
    Type: AWS::SecretsManager::Secret
    Properties:
      SecretString: '{"url":"<URL>","token":"<TOKEN>"}'
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  roleC7B7E775:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
  roleDefaultPolicy7C980EBA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - secretsmanager:DescribeSecret
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource:
              Ref: secret4DA88516
        Version: "2012-10-17"
      PolicyName: roleDefaultPolicy7C980EBA
      Roles:
        - Ref: roleC7B7E775
  flume9B71057B:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code:
        ZipFile: |-
          import boto3
          import datetime
          import json
          import os
          from botocore.vendored import requests

          def handler(event, context):

              print(event)
              #print(type(event))

              epoch = datetime.datetime.now(datetime.timezone.utc).timestamp()

              payload = {}
              payload['time'] = epoch                         # @timestamp
              #payload['timezone'] = 'Z'                      # @timezone
              #payload['index'] = 'Connector Name'            #repo
              #payload['sourcetype'] = 'Parser Name'          #type    
              #payload['source'] = 'Log Location'             # @source
              #payload['host'] = 'Origin Host'                # @host
              payload['event'] = event['body']                # @rawstring
              #payload['fields'] = {"#key":"value"}           #tags
              
              #print(payload)
              #print(type(payload))

              secretmgr = boto3.client('secretsmanager')

              secret = secretmgr.get_secret_value(
                  SecretId = os.environ['SECRET_MGR']
              )

              hec = json.loads(secret['SecretString'])

              headers = {
                  'Authorization': 'Bearer '+hec['token'],
                  'Content-Type': 'application/json'
              }

              r = requests.post(
                  hec['url'],
                  headers = headers,
                  data = payload
              )

              print(r.json())
              #print(r.status_code)

              return {
                  'statusCode': 200,
                  'body': json.dumps('Log Shipped!')
              }
      Environment:
        Variables:
          SECRET_MGR:
            Ref: secret4DA88516
      Handler: index.handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
          - roleC7B7E775
          - Arn
      Runtime: python3.13
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
      Timeout: 30
    DependsOn:
      - roleDefaultPolicy7C980EBA
      - roleC7B7E775
  logs0B6081B1:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - /aws/lambda/
            - Ref: flume9B71057B
      RetentionInDays: 14
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  apilogs9C0A78C8:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 14
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
  apiC8550315:
    Type: AWS::ApiGateway::RestApi
    Properties:
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name:
        Ref: apigatewayname
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
  apiDeployment149F129487cdf7c624a1ffa559a8eeb5bb4e2d4f:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: apiC8550315
    DependsOn:
      - apiingestPOSTE30E20E6
      - apiingest6BBF5555
  apiDeploymentStageprod896C8101:
    Type: AWS::ApiGateway::Stage
    Properties:
      AccessLogSetting:
        DestinationArn:
          Fn::GetAtt:
            - apilogs9C0A78C8
            - Arn
        Format: $context.identity.sourceIp $context.identity.caller $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId
      DeploymentId:
        Ref: apiDeployment149F129487cdf7c624a1ffa559a8eeb5bb4e2d4f
      MethodSettings:
        - DataTraceEnabled: false
          HttpMethod: "*"
          ResourcePath: /*
          ThrottlingBurstLimit: 5000
          ThrottlingRateLimit: 10000
      RestApiId:
        Ref: apiC8550315
      StageName: prod
      Tags:
        - Key: GitHub
          Value: https://github.com/jblukach/flume
  apiingest6BBF5555:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - apiC8550315
          - RootResourceId
      PathPart: ingest
      RestApiId:
        Ref: apiC8550315
  apiingestPOSTApiPermissionFlumeStackapiA7D583D9POSTingestAEEC0355:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - flume9B71057B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /
            - Ref: apiDeploymentStageprod896C8101
            - /POST/ingest
  apiingestPOSTApiPermissionTestFlumeStackapiA7D583D9POSTingest2600D5C6:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - flume9B71057B
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:us-east-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: apiC8550315
            - /test-invoke-stage/POST/ingest
  apiingestPOSTE30E20E6:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            StatusCode: "200"
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - flume9B71057B
                  - Arn
              - /invocations
      MethodResponses:
        - ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: true
          StatusCode: "200"
      ResourceId:
        Ref: apiingest6BBF5555
      RestApiId:
        Ref: apiC8550315
Outputs:
  apiEndpoint9349E63C:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: apiC8550315
          - .execute-api.us-east-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: apiDeploymentStageprod896C8101
          - /

